// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHEac3XlHJKP33KtKomMY8T5OOnngItjU',
    appId: '1:71949764472:web:07620db7ba5feda4782a8d',
    messagingSenderId: '71949764472',
    projectId: 'cool-chat-application',
    authDomain: 'cool-chat-application.firebaseapp.com',
    storageBucket: 'cool-chat-application.appspot.com',
    measurementId: 'G-2NCKBVKQG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_oQLogt9FmrGUZ4NA4Dv1y15i95zFpu4',
    appId: '1:71949764472:android:d4bcce7d9ee60f23782a8d',
    messagingSenderId: '71949764472',
    projectId: 'cool-chat-application',
    storageBucket: 'cool-chat-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB43-XzGb3a3VaT1X_cBZlLFUMmXdE_TfI',
    appId: '1:71949764472:ios:5eed273f976bdc1f782a8d',
    messagingSenderId: '71949764472',
    projectId: 'cool-chat-application',
    storageBucket: 'cool-chat-application.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB43-XzGb3a3VaT1X_cBZlLFUMmXdE_TfI',
    appId: '1:71949764472:ios:d960751418465873782a8d',
    messagingSenderId: '71949764472',
    projectId: 'cool-chat-application',
    storageBucket: 'cool-chat-application.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
